In [11]:
import pandas as pd
lse_dat=pd.read_excel('./data/LSE_dat.xlsx', sheet_name="Teaching")
lse_dat.columns = lse_dat.iloc[0]
lse_dat = lse_dat[1:]
lse_dat

,Mode of study,Level of study,Subject level,Subject code,Subject,Question,Responses,Population,Suppression reason,Option 1,...,Positivity measure (%),Benchmark (%),Difference (ppt),Standard deviation,Contribution to benchmark (%),Materially below benchmark (%),Broadly in line with benchmark (%),Materially above benchmark (%),Publication response headcount,Publication response rate (%)
1,All modes,All undergraduates,CAH1,CAH04,Psychology,Q01: How good are teaching staff at explaining...,30,30,NaN,20,...,100,93.1,6.9,3.7,1.1,0.6,11.2,88.2,30,100
2,All modes,All undergraduates,CAH1,CAH04,Psychology,Q02: How often do teaching staff make the subj...,30,30,NaN,18,...,96.7,78.8,17.8,6.1,1.1,0,0.5,99.4,30,100
3,All modes,All undergraduates,CAH1,CAH04,Psychology,Q03: How often is the course intellectually st...,30,30,NaN,19,...,100,84.9,15.1,4.7,1.1,0,0.3,99.6,30,100
4,All modes,All undergraduates,CAH1,CAH04,Psychology,Q04: How often does your course challenge you ...,30,30,NaN,20,...,100,79.6,20.4,5.1,1.1,0,0,100,30,100
5,All modes,All undergraduates,CAH1,CAH04,Psychology,Q05: To what extent have you had the chance to...,30,30,NaN,21,...,96.7,81.4,15.3,5.7,1.1,0.1,1.2,98.8,30,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4892,Full-time,First degree,All subjects,NaN,NaN,Theme 3: Assessment and feedback,1274,1892,NaN,NaN,...,71.1,74.6,-3.5,1.2,4.1,79.4,20.6,0,1275,67.4
4893,Full-time,First degree,All subjects,NaN,NaN,Theme 4: Academic support,1273,1892,NaN,NaN,...,87.4,85.2,2.2,1,4.1,0,63.9,36.1,1275,67.4
4894,Full-time,First degree,All subjects,NaN,NaN,Theme 5: Organisation and management,1274,1892,NaN,NaN,...,80.7,79.6,1.1,1.1,4.1,0.1,88.4,11.5,1275,67.4
4895,Full-time,First degree,All subjects,NaN,NaN,Theme 6: Learning resources,1268,1892,NaN,NaN,...,87.1,87.6,-0.5,0.9,4.1,1.8,98.2,0,1275,67.4
4896,Full-time,First degree,All subjects,NaN,NaN,Theme 7: Student voice,1266,1892,NaN,NaN,...,67.2,73.1,-5.8,1.2,4.1,99.6,0.4,0,1275,67.4